### ISSUE TITLE
Style Improvement

### ISSUE THREAD

**Issue by chaanakyaaM** [Rajan-Barnwal/jobproject#125]
Hello,
I would like to change the icon of the website , name of the website and also make the nav bar responsive, including hover effects

![Screenshot (195)](https://github.com/Rajan-Barnwal/jobproject/assets/131477601/cd23b16a-7b5e-4e39-83a4-205382e3463e)

Could you assign it to me ?

**Comment by nsk6704** [comment]
I kindly request you to assign this issue to me, an aspiring web developer certified by freeCodeCamp in Web Design and have also interned at a company named Codsoft.

Also I have contributed to roadmap.sh, which is one of the most starred repository on GitHub!!

Here is my LinkedIn Profile for more information!

https://www.linkedin.com/in/saketh-kashyap-nagendra/

**Comment by aasthax1** [comment]
Please assign this task to me. I am a creative person and have good experience in making attractive websites. Thank you.
