### ISSUE TITLE
To make the Navbar sticky and below navbar to fix banner part as a sticky.

### ISSUE THREAD

**Issue by sakeel-103** [Rajan-Barnwal/jobproject#140]
Please assign this issue to me .
Navbar is not working accordingly.
So, if you assign me , I can fix these things.

https://github.com/Rajan-Barnwal/jobproject/assets/136844498/b09b771e-2f51-4fcd-8584-b57d1ea8528f

**Comment by KhushiParekh28** [comment]
please assign me this issue under GSSoc contributer
