### ISSUE TITLE
No proper alignmnet of Signin and Signup in Nav bar

### ISSUE THREAD

**Issue by Anjaliavv51** [Rajan-Barnwal/jobproject#142]
Hello PA
![image](https://github.com/Rajan-Barnwal/jobproject/assets/154777864/42eb1abf-0e3c-4e45-9d76-c506ea0cc934)
I would like to make those two button look great & want to re align the nav bar.

I would like to fix this!!!
Assign this issue under GSSOC'24.

**Comment by Vibhuti270** [comment]
hey..
Please assign this task to me.
Thanks
