### ISSUE TITLE
Adding hovering effect on cards and buttons

### ISSUE THREAD

**Issue by Joy-Agrawal** [Rajan-Barnwal/jobproject#16]
I've noticed that the feature card and 'Learn More' buttons currently lack hovering effects. 
Implementing hover effects would enhance the liveliness of these elements and contribute to the overall attractiveness of the website. 
This improvement would positively impact the UI/UX.

**Comment by Joy-Agrawal** [comment]
please assing this issue to me

**Comment by riyasaxena32** [comment]
i can solve this issue..it is really a short task..plaese assign this issue to me

**Comment by rajsingh19** [comment]
I am experienced in web development, having designed various websites and contributed to college club websites. I can solve issues by adding hovering effects on card and button. Please assign me this issue I am giving you my best.

**Comment by BhargavTammana** [comment]
Hi, I have pretty good ideas about the hovering effects can you assign this issue to me

**Comment by Joy-Agrawal** [comment]
Hello PA
Fixed the issue no : https://github.com/Rajan-Barnwal/jobproject/issues/13

How to fix:
Used Transform , scale and transition properties
Used  Transition and transition-delay for maintaining a smooth transition
now properly working

before : 
![hover before](https://github.com/Rajan-Barnwal/jobproject/assets/104222673/3f70c7b0-d040-4b17-90a5-5dcd5d78142e)

After : 
![hover after](https://github.com/Rajan-Barnwal/jobproject/assets/104222673/453ca11b-d826-4102-8100-902931f8813b)

**Comment by hussain123sahil** [comment]
I can solve this issue. Please assign me this issue.
