### ISSUE TITLE
Change css of sign in and sign up page

### ISSUE THREAD

**Issue by 39palakved** [Rajan-Barnwal/jobproject#182]
need to change css of sign in and sign up page . so that it will look attractive .

**Comment by 39palakved** [comment]
please assign this task to me.

**Comment by Akshitha28112004** [comment]
Hey I'm a ggssoc'24 contributor. Can you please assign me this issue ?

**Comment by MrudulaTeegala** [comment]
@Rajan-Barnwal kindly assign this issue to me and mark issue as GSSOC with its level

**Comment by Akshitha28112004** [comment]
I didn't understand the mail you sent . Did you assign that issue to me ?



Thanks & Regards
Akshitha Panchadi

**Comment by VarshiniMallidi** [comment]
I would like to add fields for first name, last name, email, and password, along with an option to sign up using Google in the sign up page and in the sign in page with username or email id and password,forgot password option and will add the company logo.Additionally, ensure the page is visually appealing using CSS.Please assign the issue to me and mark the issue with GSSoC24 label and its level

**Comment by chakrabortydeep** [comment]
![image](https://github.com/Rajan-Barnwal/jobproject/assets/146315717/70d359f4-50a4-40d3-ac37-dffbfc8b88ea)
 
I can fix that Sign in and Sign up effects and I also done that in so many projects of mine recently so I can do that efficiently as per your required style.

**Comment by manishprasad9156** [comment]
I have earlier made an login page I can do the same for you please assign me this task to upgrade this login page.

My work sample is in the following screenshot
![Login Page](https://github.com/Rajan-Barnwal/jobproject/assets/160319743/aed1a5c6-768e-4ce8-a820-ee7c2223794f)
