### ISSUE TITLE
Navbar needs to be updated

### ISSUE THREAD

**Issue by Varnika2526** [Rajan-Barnwal/jobproject#191]
The navbar section is not placed correctly and width needs to be changed , Speaking Concisely Styling needs to be done on the navbar
@Rajan-Barnwal Kindly assign me this issue under GSSOC'24 , I believe I can resolve this issue.

**Comment by Mahy-31** [comment]
Hello there. As a GSSOC'24 contributor and front-end web developer, I would like to take up this task. Kindly let me resolve this issue and make it look better. Thank you

**Comment by rishmiiee26** [comment]
Can you please assign me this to solve it? Being a GSSOC'24 contributor, looking forward to get a chance to create some changes. Thank you

**Comment by Siwanikaushik** [comment]
JOB WEBSITE
Hii @Rajan-Barnwal ,
ISSUE : Navbar is not at its proper place & not working properly.
What I can do ??
I am a contributor at @GSSOC'24 . I have good knowledge of HTML & CSS , also I have made a website using HTML & CSS, so I can resolve this issue of navbar & can make the navbar work properly.
So I request you to assign me this issue.

**Comment by MrudulaTeegala** [comment]
@Rajan-Barnwal kindly assign this issue to me and mark issue as GSSOC and its level

**Comment by hritika2409** [comment]
Hey.I can help you with this please assign me this task under GSSoC'24  as a contributor.

**Comment by SHANMUGAPRIYA-1** [comment]
will you assign this task to me

**Comment by Rajan-Barnwal** [comment]
Ok i assign this task to you all three ok

**Comment by hritika2409** [comment]
@Rajan-Barnwal  Thank you so much for assigning me this task,I will get back to you with the assigned work in couple of days.
