### ISSUE TITLE
 Add a Job Feed Section 

### ISSUE THREAD

**Issue by MastanSayyad** [Rajan-Barnwal/jobproject#212]
Hi @Rajan-Barnwal ,

I've been exploring the website, It **doesn't look like a job searching portal** and I believe that adding a **job feed section** to the job portal would significantly enhance the user experience and make it resemble a typical job website. Having a dynamic job feed to the webiste showcases available **job opportunities** to the users. Additionally I would like to **style the vertical Scrollbar** to look more engaging.

**Benefits:**
- A job feed section provides users with easy access to the latest job listings.
- Users to interact with the website more frequently, increasing user engagement.
- Real-world resemblance.
- Many more.

I'd like to take on the task, Could you please **assign this issue to me under GSSoC 24** so I can contribute to the project?

**Comment by hritika2409** [comment]
Hey.I can help you with this please assign me this task under GSSoC'24  as a contributor.
