### ISSUE TITLE
Bug in NavBar, Need to corrected

### ISSUE THREAD

**Issue by Bhavishya2601** [Rajan-Barnwal/jobproject#230]
The navbar should have full width of 100% so that it can cover the whole screen vertically and also the picture behind it is hiding due to navbar, I will correct it out
![Screenshot 2024-05-16 214722](https://github.com/Rajan-Barnwal/jobproject/assets/147748752/80e60cfc-6bea-4cbf-9f7c-cb808dd42f29)

Hope you will assign this task to me

**Comment by KARTHIK174** [comment]
Please Assign this issue to me as i am contributing to this under GSSoC'24.

**Comment by Bhavishya2601** [comment]
Brother I am also contributing under gssoc
