### ISSUE TITLE
Footer is not responsive 

### ISSUE THREAD

**Issue by nagalakshmi08** [Rajan-Barnwal/jobproject#249]
Hello, the footer is not responsive in mobile phones. The text is going out of the website.
![Screenshot_20240518_230251](https://github.com/Rajan-Barnwal/jobproject/assets/121669832/459702d8-6c78-4701-b25f-a1a1d6154622)
I would like to solve this task. Please assign me this issue, I want to contribute to this project under GSSoC'24.

**Comment by NEKKALAPUSIVASATYASAILIKHITHA** [comment]
Hi, I'd like to work on this issue. Can you assign it to me?

**Comment by Rajan-Barnwal** [comment]
ok
