### ISSUE TITLE
Feat: Add "Back to Top" Button on Homepage

### ISSUE THREAD

**Issue by AsmitaMishra24** [Rajan-Barnwal/jobproject#290]
Describe the feature:
The addition of a "Back to Top" button on the homepage of our website would enhance user experience by providing a convenient way for users to quickly return to the top of the page after scrolling down. This feature is commonly seen on many websites and has become an expected element for smooth navigation.

Screenshots of my previous work: 
![332186194-b7b10ef3-911a-4da0-a4f0-d13343378128](https://github.com/Rajan-Barnwal/jobproject/assets/146121869/61d635f5-cac6-4a1b-b609-44147ef1e941)
![332186184-b2297297-184c-4a61-b303-42c1894856d8](https://github.com/Rajan-Barnwal/jobproject/assets/146121869/708541ce-8897-4eb7-ab31-586c0c91360b)

**Comment by AsmitaMishra24** [comment]
I would like to address this issue as part of GSSOC'24. Please assign it to me.

**Comment by Ananya-Nair20** [comment]
Hello 

I am participating in GSSOC'24. I am interested in resolving this issue. Please assign this issue to me under GSSOC'24 with appropriate level labels.

Thank you
