### ISSUE TITLE
DarkMode for all pages

### ISSUE THREAD

**Issue by Prithwi32** [Rajan-Barnwal/jobproject#358]
-currently darkmode theme is not applied for all pages..
i would like to work on this issue under gssoc'24

**Comment by Prithwi32** [comment]
@Rajan-Barnwal  could you assign this issue to me under gssoc and with level label

**Comment by RahulNaha** [comment]
@Rajan-Barnwal Willing to work .Please assign this issue to me. I am  a GSSOC24 Contributor
