### ISSUE TITLE
Feature💡: Add "Privacy Policy" and "Terms and Conditions" Pages to Footer

### ISSUE THREAD

**Issue by aslams2020** [Rajan-Barnwal/jobproject#394]
Hey @Rajan-Barnwal,
Here is the feature i want to suggest - 

i want **to create and add two separate pages** in the website's footer by adding links to two new pages: 
Terms and Conditions and Privacy Policy.
These pages are essential for informing users about the legal aspects of using our site and ensuring compliance with privacy regulations.

As you can see, **currently there is no Dedicated pages** and links to the footer section's important links -

![image](https://github.com/Rajan-Barnwal/jobproject/assets/131389695/d1ed64db-7f2c-4591-a786-7a486d1e835b)

**What will i do?**
1. Create a Terms and Conditions Page.
2. Create a Privacy Policy Page.
3. Update Footer:  Add links to the newly created "Terms and Conditions" and "Privacy Policy" pages in the website's footer.

@Rajan-Barnwal, Could you please assign me this issue under GSSoC'24? 
Thankyou!

**Comment by aslams2020** [comment]
@Rajan-Barnwal

**Comment by RahulNaha** [comment]
@Rajan-Barnwal Willing to work .Please assign this issue to me. I am  a GSSOC24 Contributor

**Comment by aslams2020** [comment]
@Rajan-Barnwal Please take a look!
