### ISSUE TITLE
hover effect to logos

### ISSUE THREAD

**Issue by paulkrishanu4** [Rajan-Barnwal/jobproject#60]
I want to add hover effect to the logos. Please assign me this issue under gssoc'24

Before: 

https://github.com/Rajan-Barnwal/jobproject/assets/169196836/151e6cae-6bd8-4bad-b4ff-50c2edd15104

After:

https://github.com/Rajan-Barnwal/jobproject/assets/169196836/ab131d29-3279-469c-87b7-340b0b4cc7f7

**Comment by Sheryar-bit** [comment]
Ok I will work on this

**Comment by Ayushvishwakarma04** [comment]
Hello! 😊 I'd appreciate being assigned this task under GSSoC 24.

**Comment by AnandK-pm** [comment]
Hello . I'm eager to work on this issue. Please assign me the issue.

**Comment by FatemaBaig** [comment]
Hello sir,
This  hover effect , part of project i would like to work on this please assign it to me.
