### ISSUE TITLE
Navbar not aligned properly on the top

### ISSUE THREAD

**Issue by Sibam-Paul** [Rajan-Barnwal/jobproject#83]
### The Navbar I think is not aligned and made fixed properly on the top

**Image Reference**
![image](https://github.com/Rajan-Barnwal/jobproject/assets/158052549/1d901b54-774c-45fc-a3fb-d1bdec47cbc8)

**Proposed changes **
From the Pic I will align the navbar and make it function properly

**Want to work on this issue **
_Please assign this issue under GSSOC'24 and give necessary tags on the issue_

**Comment by richasriva** [comment]
Hi, I can fix this issue properly. Kindly assign this issue to me.

**Comment by AmrutaZagade** [comment]
I am participating in GSSOC'24 and I am interested in this issue, Could you please assign me.

**Comment by shwetamishra4** [comment]
hello  , as  NAVBAR NOT ALIGNED PROPERLY ON THE TOP please assign this issue to me I will do my best to fix it.
