### ISSUE TITLE
[Bug] The facebook and twitter icon are working

### ISSUE THREAD

**Issue by Sibam-Paul** [Rajan-Barnwal/jobproject#84]
### The Facebook and twitter icons on the footer are not redirecting  to website Facebook and twitter account

**Image reference**
![image](https://github.com/Rajan-Barnwal/jobproject/assets/158052549/bc2e58e3-239b-426d-8917-fc7358187ca2)

**Will do the certain changes if u can **assign** me this issue **
_Please give necessary tags under GSSSOC'24_

_Also tell me where to contact you _

**Comment by KeerthiPippalla** [comment]
I would like to work on it. Please assign me. GSSOC'24.

**Comment by mohit2202solanki** [comment]
Hello , Please assign this issue to me and provide the labels for the issue .

**Comment by SHIRISH-30** [comment]
I would like to work on it. Please assign me. GSSOC'24.
