### ISSUE TITLE
UI of sign in/ sign up page

### ISSUE THREAD

**Issue by Madhuri36** [Rajan-Barnwal/jobproject#89]
Sign in and sign up pages lacks UI and I would like to add it. 
@Rajan-Barnwal Please assign this to me under GSSoC'24.

**Comment by AmrutaZagade** [comment]
Hi @Rajan-Barnwal I am participating in GSSOC'24 and I am interested in this issue, Could you please assign me.

**Comment by Roy-Soumik** [comment]
please assign this task to me, please add the gssoc 2024 label

**Comment by Deepu8238** [comment]
hi @Rajan-Barnwal !
sign up and sign in page are so simple  it  would be beautiful and attractive to the user if we add some UI designs 
so i would like to design the UI for the sign in and sign up page to make it more attractive to the user.
please assign this to me under GSSOC 2024
