### ISSUE TITLE
Changing the title in the tab of the website to "Job Project"

### ISSUE THREAD

**Issue by Sibam-Paul** [Rajan-Barnwal/jobproject#95]
### Hey I think mentioning the name of the Project "Job Project" in place of "My Project" Will be better 

**Image Reference where to change**
![image](https://github.com/Rajan-Barnwal/jobproject/assets/158052549/658f4f9d-ac13-4a88-ba54-a759be7a5bf9)

**Please Do assign me this issue so that I can start Contributing**

**Please give necessary tags to this issue under GSSOC'24 and mention Level as part the program good practice**
_Thank you_

**Comment by deepuzz11** [comment]
I would like to contribute

**Comment by sonarani1** [comment]
I can fix this issue properly, kindly assist me with this project.

**Comment by Roy-Soumik** [comment]
please assign this task to me, please add the gssoc 2024 label

**Comment by drashtigit** [comment]
Please assign this issue to me. Would be happy to do it.
